make: imgui implot
	c++ -o dashboard *.cpp -lSDL2 -Iimgui -lGL -Ilib/logger

imgui:
	echo "Building Imgui"
	c++  imgui/backends/imgui_impl_sdl2.cpp imgui/backends/imgui_impl_opengl2.cpp imgui/*.cpp -lSDL2 -lGL

implot:
	echo "Building Implot"
	c++ implot/implot.cpp